kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  # Name of ImageStream + -build-config
  name: myemm-ear-build-config
  namespace: mas-inst8809-manage
spec:
  nodeSelector: null
  output:
    to:
      # Same name as ImageStream
      kind: ImageStreamTag
      name: 'myemm-ear:v1'
  resources:
    limits:
      ephemeral-storage: 100Gi
    requests:
      ephemeral-storage: 30Gi
  strategy:
    type: Docker
    dockerStrategy:
      pullSecret:
        name: ibm-entitlement
      env:
        - name: DEPLOY_GATEWAY_URL
          value: >-
            https://1qbx7rd5w9.execute-api.us-east-1.amazonaws.com/default/ezmax-deploy?key=ezmaxmobile.zip
        # This token will be different for each client
        - name: DEPLOY_TOKEN
          value: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJidWNrZXQiOiJ0ZXN0LWVtbS1kZXBsb3ltZW50cyIsImtleVJlZyI6Ii4qZXptYXhtb2JpbGVbXi9dKiQifQ.-Npu7D9vSUxZkTEbmDrNgdBswmR8E3U6K-PN95yyJ9o
      forcePull: true
  postCommit: {}
  source:
    type: Dockerfile
    dockerfile: >
      FROM cp.icr.io/cp/manage/manageadmin:8.4.5 AS ADMIN


      ENV MXE_MASDEPLOYED=1

      ENV MXE_USESQLSERVERSEQUENCE=1

      ENV LC_ALL=en_US.UTF-8

      ENV LANGUAGE_BASE=en

      ENV LANGUAGE_ADD=

      COPY --chown=maximoinstall:0 additional-server-files/
      /opt/IBM/SMP/maximo/additional-server-files

      WORKDIR /opt/IBM/SMP/maximo/tools/maximo

      COPY --chown=maximoinstall:0 maximo-all-server/
      /opt/IBM/SMP/maximo/deployment/was-liberty-default/deployment/maximo-all/maximo-all-server

      WORKDIR /opt/IBM/SMP

      # Get download URL from deploy gateway, then download and build EMM ear

      RUN \
        EMM_URL=$(wget -q -O - --header="Authorization: Bearer $DEPLOY_TOKEN" "$DEPLOY_GATEWAY_URL") &&\
        wget -O ezmaxmobile.zip -c "$EMM_URL" &&\
        unzip ezmaxmobile.zip &&\
        cd ezmaxmobile &&\
        chmod u+x ./buildemmear.sh &&\
        ./buildemmear.sh &&\
        ls -al default &&\
        ls -al was-liberty-default &&\
        ls -al was-liberty-default/emm-server/apps &&\
        ls -al /opt/IBM/SMP/maximo/deployment/was-liberty-default/deployment/maximo-all/maximo-all-server &&\
        ls -al /opt/IBM/SMP/maximo/additional-server-files

      WORKDIR /opt/IBM/SMP/maximo/tools/maximo

      #CMD sleep 123456789

    images:
      - from:
          kind: ImageStreamTag
          # Instance name + -masdev-admin:latest
          name: 'inst8809-masdev-admin:latest'
        paths:
          - sourcePath: >-
              /opt/IBM/SMP/maximo/deployment/was-liberty-default/deployment/maximo-all/maximo-all-server
            destinationDir: .
          - sourcePath: /opt/IBM/SMP/maximo/additional-server-files
            destinationDir: .
    secrets:
      - secret:
          name: inst8809-masdev-manage-truststorepasswd
        destinationDir: tmp_build_files
    configMaps:
      - configMap:
          name: inst8809-masdev-truststore-cfg
        destinationDir: tmp_build_files
  runPolicy: Serial
