apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: myemm-liberty-build-config
  namespace: mas-inst8809-manage
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'myemm-liberty:v1'
  resources:
    limits:
      ephemeral-storage: 50Gi
    requests:
      ephemeral-storage: 10Gi
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      pullSecret:
        name: ibm-entitlement
      forcePull: true
  postCommit: {}
  source:
    type: Dockerfile
    dockerfile: >
      FROM cp.icr.io/cp/manage/ubi-wlp-manage:2.2.13 AS LIBERTY


      #ARG VERBOSE=true


      COPY --chown=1001:0 emm-server/apps/  /config/dropins

      RUN rm /opt/ibm/wlp/usr/servers/defaultServer/server.env && mkdir
      /managefiles/additional-server-files


      COPY --chown=1001:0 additional-server-files/
      /managefiles/additional-server-files/


      ENV MXE_MASDEPLOYED=1

      ENV MXE_USESQLSERVERSEQUENCE=1

      ENV LC_ALL=en_US.UTF-8

      USER 1001


      # This is overridden by container cmd when deployed in OpenShift

      # CMD /opt/ibm/wlp/bin/server run defaultServer

      CMD sleep 123456789
    images:
      - from:
          kind: ImageStreamTag
          name: 'myemm-ear:v1'
        paths:
          - sourcePath: >-
              /opt/IBM/SMP/ezmaxmobile/was-liberty-default/emm-server
            destinationDir: .
          - sourcePath: /opt/IBM/SMP/maximo/additional-server-files
            destinationDir: .
  triggers:
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: 'myemm-ear:v1'
  runPolicy: Serial
